### ISSUE TITLE
AudioTranscriptionRequest.Temperature property should be of float? type

### ISSUE THREAD

**Issue by newbieGameDev** [RageAgainstThePixel/com.openai.unity#103]
Hi! I am testing the whisper model and when I request audio transcription, I want to add temperature and language parameters. I can add temperature but it is set to integer and it has to float as far as I know from this doc; [API reference page](https://platform.openai.com/docs/api-reference/audio/createTranscription#temperature), I want to set it low like 0.1f to avoid hallucinations.
As for the language, I want to set it to English to improve accuracy but I couldn't find it in the parameters of the request function.
How can this issue be resolved?
Thanks in advance.

**Comment by StephenHodgson** [comment]
[Please review the docs in the main readme](https://github.com/RageAgainstThePixel/com.openai.unity/tree/main#create-transcription).
You can add temperature and language when you create the request for the audio transcription.

for example:
```csharp
var api = new OpenAIClient();
var request = new AudioTranscriptionRequest(audioClip, temperature: 0.1f, language: "en");
var result = await api.AudioEndpoint.CreateTranscriptionAsync(request);
Debug.Log(result);
```

**Comment by newbieGameDev** [comment]
Yes, I tried that but I get errors like this;
When I write this line: `var request = new AudioTranscriptionRequest(audioClip, temperature: 0.1f, language: "en");`, get this error; "The best overload for 'AudioTranslationRequest' does not have a parameter named 'language'".
Then when I write the line like this; `request = new AudioTranslationRequest(audioClip, temperature: 0.1f);`, get this erors;
"Argument 1: cannot convert from 'UnityEngine.AudioClip' to 'string'" this for the audioClip, 
and this for the temperature; " Argument 2: cannot convert from 'float' to 'int?'"
Btw I use Unity 2021.3.29f1

**Comment by StephenHodgson** [comment]
Ah I see what you mean. The type should be a `float?` not `int?`

**Comment by newbieGameDev** [comment]
Thank you for solving this issue. I updated and tried it but I am having issues with nullable float(float?). When I request transcription like this;
```
float? temperatureValue = 0.1f;
public async void TranscriptAudio(){
      AudioTranscriptionRequest transcriptionRequest = new AudioTranscriptionRequest(
          audioPath,
          model: "whisper-1",
          responseFormat: AudioResponseFormat.Json,
          temperature: temperatureValue,
          language: "en"
      );

      result = await api.AudioEndpoint.CreateTranscriptionAsync(transcriptionRequest);
      canvas.UpdateTranscriptedText(result);
}
```
I get this error; 
```
[Body]
{
  "error": {
    "message": "1 validation error for Request\nbody -> temperature\n  value is not a valid float (type=type_error.float)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
[Errors]
HTTP/1.1 400 Bad Request
```
Even tho I when I write like this  `temperature: (float?)0.1f,` or this ` temperature: 0.1f,` I get the same error.
How can I solve this?

**Comment by StephenHodgson** [comment]
you shouldn't need to cast it to `(float?)`

**Comment by StephenHodgson** [comment]
Some feedback on your code snippet:

- be sure to always wrap any async call from a MonoBehaviour in a `try/catch` 
- I updated the example to use an audio clip, since the asset will already be loaded into memory and much easier to use
- I added a transcription callback for you to make it easier to signal the canvas to update its text, although tbh you should just have a direct serialized reference to the text component and use that instead.

```csharp
using OpenAI;
using OpenAI.Audio;
using System;
using UnityEngine;

public class NewBehaviourScript : MonoBehaviour
{
    [SerializeField]
    private float temperature = 0.1f;

    private OpenAIClient api;

    private void Awake()
    {
        api = new OpenAIClient();
    }

    public async void TranscriptAudioAsync(AudioClip clip, Action<string> transcriptionCallback = null)
    {
        try
        {
            AudioTranscriptionRequest transcriptionRequest = new AudioTranscriptionRequest(
                clip,
                responseFormat: AudioResponseFormat.Json,
            temperature: temperature,
            language: "en");

            var result = await api.AudioEndpoint.CreateTranscriptionAsync(transcriptionRequest);
            transcriptionCallback?.Invoke(result);
            // canvas.UpdateTranscriptedText(result);
        }
        catch (Exception e)
        {
            Debug.LogError(e);
        }
    }
}
```

**Comment by newbieGameDev** [comment]
Thank you very much for your advice, I will try to implement them. There is a lot I don't know since I'm new to this field. 

I tried as you wrote, but unfortunately, I'm still getting the same error. Whether I write it as a float or as a nullable float, I'm still encountering the same error. However, I didn't get this error when I wrote 'null'.
