### ISSUE TITLE
Unable to generate image in Unity android and ios build

### ISSUE THREAD

**Issue by ArsalanRizwan** [RageAgainstThePixel/com.openai.unity#106]
# Bug Report

## Overview
I am having an issue in Unity android and ios build for an AR app.
The code to generate image in realtime works fine in unity editor and in the Windows build. But once I build the app for android and ios the image doesn't gets generated. After debugging I have found out that the request does gets sent from both android and ios but it doesn't send the prompt that's used for image generation. Error says "prompt is a required property" and its 400 bad request error. I think there is  a bug in the GenerateImageAsync function of the ImagesEndpoint class that causes this behavior.

## To Reproduce
1. Create a 3D unity project with a cube that has a material.
2. Create a canvas in the scene with an input field for prompt and a button to send request to api for image generation.
3. After image is generated and downloaded set the texture of the material that is attached to cube to the generated image to see result.
4. Build the app for android or ios and test the same behavior on your device. The image won't get generated and the error will be present in logs that prompt is a required property meaning that it isn't being sent from app. The error message can also be seen by displaying it in a text field in the scene.

## Expected behavior
I expected that the image would be generated in the both the android and ios build as it gets generated in the Unity Editor and in the Windows build.
![WhatsApp Image 2023-08-29 at 1 28 08 AM](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/71985327/8d0baeb1-9bfb-466b-ba30-3a6bba937263)

**Comment by ArsalanRizwan** [comment]
Thank you this fixed it. The build was indeed stripping the types required for serialization. I had to change the Managed Stripping Level property in player settings  from low to minimal and after rebuilding it worked in both ios and android.

**Comment by StephenHodgson** [comment]
Great, thanks for the report. I'll be sure to add additional attributes to prevent this stripping in the library so that manual changes to the stripping level is not required.
