### ISSUE TITLE
Please add instructions to how to serialize a request/message

### ISSUE THREAD

**Issue by tomkail** [RageAgainstThePixel/com.openai.unity#111]
Hello! It's often handy to serialize a request so you can use it later. However, using standard Json.Net settings to serialize results in an error. After a bit of digging. I found `client.JsonSerializationOptions`, but it's internal. Can I suggest making it/something similar accessible and including a section on serialization in your docs?

**Comment by tomkail** [comment]
Ah, and a bug - ChatRequest contains this line
`public override string ToString() => JsonConvert.SerializeObject(this);`
This results in an error because it's not using your serialization settings. Json.Net default settings can be overridden too, so you should explicitly state the settings you want to use.

**Comment by StephenHodgson** [comment]
I think I removed that in https://github.com/RageAgainstThePixel/com.openai.unity/pull/109 and made the json serialization settings an internal static member

**Comment by tomkail** [comment]
Ah ok. We’re on latest but I guess that commit isn’t on main yet or
something. Any chance you can make the serialiser settings public and
include it in the docs? It’s handy! Happy to make a pr if you’re busy.

**Comment by StephenHodgson** [comment]
I do not wish to make it public

**Comment by tomkail** [comment]
Ok! Is there a way to solve this problem you’d recommend?

**Comment by StephenHodgson** [comment]
it should be fixed on next release
