### ISSUE TITLE
<_UIKBFeedbackGenerator: 0x28240bd00>: Couldn't update haptics muting for dictation audio recording. No engine.

### ISSUE THREAD

**Issue by yosun** [RageAgainstThePixel/com.openai.unity#113]
# Bug Report

## Overview
when dictation on keyboard is attempted this occurs  
<_UIKBFeedbackGenerator: 0x28240bd00>: Couldn't update haptics muting for dictation audio recording. No engine.

## To Reproduce
1. Build to iOS device
2. try to input text using the mic for dictation
3. notice the static

## Expected behavior
the static should not sound
should not see this in xcode

**Comment by StephenHodgson** [comment]
Unsure how this is related to my package.

**Comment by yosun** [comment]
Sorry, this was for your eleven labs unity plugin
