### ISSUE TITLE
TTS on Android

### ISSUE THREAD

**Issue by wouterswim** [RageAgainstThePixel/com.openai.unity#118]
Dear, 
First of all, love your package!! Most complete one I have tried :)

I can't seem to get TTS running on Android (Meta Quest 3).
Works perfectly in unity editor 2022.3.10f1
Suspect the cacheDirectory in AudioEndpoint to be the issue? 
Although I would have to do further debugging to verify.

Cheers, Wim

**Comment by wouterswim** [comment]
this is the error I get in debug: Autoconnected Player "Autoconnected Player" IOException: Read-only file system

**Comment by wouterswim** [comment]
I'm also generating mp3 files for input in the transcribe, and temp saving them to: 
File.WriteAllBytes(Application.persistentDataPath + "/mp3File.mp3", mp3);
This works fine...

**Comment by StephenHodgson** [comment]
What happens when you disable code stripping?

**Comment by StephenHodgson** [comment]
I doubt it's the caching mechanism because I use it on my quest film production pipelines
