### ISSUE TITLE
Scanning for OpenAIConfiguration resources is very slow when one doesn't even exist

### ISSUE THREAD

**Issue by frankcarey** [RageAgainstThePixel/com.openai.unity#123]
# Bug Report

## Overview
When loading the client for the first time, it causes some serious frame stutters (1-2s on my beefy machine). It seems related to the use of Resources.LoadAll on line 18 in OpenAISettings.cs. After which it seems to cache the value.

https://github.com/RageAgainstThePixel/com.openai.unity/blob/6d9f013dca4455f0ef5438c4aa4f2a317406e6b3/OpenAI/Packages/com.openai.unity/Runtime/OpenAISettings.cs#L18

Seems we can just provide our own settings to avoid this call as shown in the README

```csharp
var auth = new OpenAIAuthentication("sk-apiKey");
var settings = new OpenAISettings(resourceName: "your-resource-name", deploymentId: "deployment-id", apiVersion: "api-version");
var api = new OpenAIClient(auth, settings);
```

But perhaps it would be better to force passing in the specific scriptableObject if that's what a developer wants to use.

At minimum, calling out the performance hit for not passing in settings manually in the README would be helpful.

Thanks for making a library that's up to date!

**Comment by StephenHodgson** [comment]
Thanks for the report.

Yeah I just wanted to make it as easy as possible for developers to hit the ground running.

I'll look into possibly optimizing this with `OpenAIConfiguration` parameter overload.

**Comment by frankcarey** [comment]
Makes sense. I like the idea of loading defaults so you wouldn't have to pass in settings if you don't need to.. IMO there should just be an independent Constructor if you wanna use the scriptable object. 

On the bright side, that extra scan did identify a few legacy scriptable objects with missing monobehaviours :P

![image](https://github.com/RageAgainstThePixel/com.openai.unity/assets/377330/e485bbb9-437e-4eaa-b061-e8f6d90ccb6d)

**Comment by StephenHodgson** [comment]
Ideally you shouldn't be using embedded credentials anyway.

You should probably use a proxy server that exchanges a session token for your users.
