### ISSUE TITLE
Easily Swap Endpoints to non OpenAI/Microsoft sources

### ISSUE THREAD

**Issue by yosun** [RageAgainstThePixel/com.openai.unity#125]
# Feature Request

## Is your feature request related to a problem? Please describe.
Easily Swap Endpoints to non OpenAI/Microsoft sources

## Describe the solution you'd like
Something that does not require going in your `OpenAISettingsInfo` and manually replacing `internal const strings`

## Describe alternatives you've considered

Maybe simply exposing endpoint url in inspector 

Also ideally more easily editable schema mapping

## Additional context

Lots of solutions other than OpenAI/MS providing streaming chat completions etc.

**Comment by StephenHodgson** [comment]
You can create as many instances of OpenAIClient as you need with custom settings to fulfill this purpose.

**Comment by StephenHodgson** [comment]
For example:

```csharp
// OpenAI 
var openai = new OpenAIClient(apikey);

// Custom proxy
 var authToken = await LoginAsync();
var auth = new OpenAIAuthentication($"sess-{authToken}");
var settings = new OpenAISettings(domain: "api.your-custom-domain.com");
var proxyAI = new OpenAIClient(auth, settings);
// Azure OpenAI gpt3.5-turbo
var azureAuth = new OpenAIAuthentication("sk-apiKey");
var azure35TurboSettings = new OpenAISettings(resourceName: "gpt-3.5-turbo", deploymentId: "deployment-id", apiVersion: "api-version");
var api35Turbo = new OpenAIClient(azureAuth, azure35TurboSettings);
// Azure gpt 4
var azuregpt4Settings = new OpenAISettings(resourceName: "gpt-4", deploymentId: "deployment-id", apiVersion: "api-version");
var apiGpt4 = new OpenAIClient(azureAuth, azuregpt4Settings);
