### ISSUE TITLE
Message.Contents was a string and is now an object

### ISSUE THREAD

**Issue by isurfraz** [RageAgainstThePixel/com.openai.unity#126]
How is Message.Contents expected to be handled now? Delta.Contents is still a string but not the case for Message

Please show an example of how streaming chat using Message.Contents should work, as the example on the github readme is now invalid

**Comment by StephenHodgson** [comment]
I'll update docs soon with next release.

for now just use `ToString()` to get content.

**Comment by isurfraz** [comment]
Thank you

**Comment by StephenHodgson** [comment]
The problem is that is could be a function call, which is a completely different type.
