### ISSUE TITLE
Add Assistants Endpoint

### ISSUE THREAD

**Issue by StephenHodgson** [RageAgainstThePixel/com.openai.unity#127]
Implement api endpoints for assistants

https://platform.openai.com/docs/api-reference/assistants

**Comment by momintlh** [comment]
Waiting for this one!

**Comment by MathiasSchjoedt-Bavngaard** [comment]
First of all great work! 
This is so nice in the OpenAI-DotNet. Do you have a timeline for when this is in the Unity package?  
Best regards,

**Comment by StephenHodgson** [comment]
> First of all great work! This is so nice in the OpenAI-DotNet. Do you have a timeline for when this is in the Unity package? Best regards,

Hopefully by end of week, but no promises.
