### ISSUE TITLE
ChatEndpoint GetCompletionAsync sending wrong headers on webGL?

### ISSUE THREAD

**Issue by aherbig** [RageAgainstThePixel/com.openai.unity#137]
I run into an issue in my webGL build.

When using the ChatEndpoint.GetCompletionAsync method, I receive this exception:

> Reason: Utilities.WebRequestRest.RestException: <b>[500]</b> <color="cyan">https://oai-dream-shared-stg.openai.azure.com/openai/deployments/$my_resource_name$/chat/completions?api-version=2023-03-15-preview</color> <color="red">Failed!</color>
> [Headers]
> Invalid Headers: Invalid Headers
> [Errors]
> Unknown Error
> 
>   at Utilities.WebRequestRest.Rest.Validate (Utilities.WebRequestRest.Response response, System.Boolean debug, System.String methodName) [0x00000] in <00000000000000000000000000000000>:0 

Non webGL everything works fine. I am currently trying to find out which headers are being sent, and if they are different to the ones being sent on non-webgl.

**Comment by aherbig** [comment]
Yes it is.

I think it is a CORS issue and I am currently checking with my colleagues to add my requests to our CORS policy. Will follow up once I know how that worked out.

**Comment by aherbig** [comment]
Ohh, so we could fix it by including the url in our CORS Policy, so my issue has been sorted out. Sorry for the troubles!

**Comment by StephenHodgson** [comment]
No worries, great to know in case anyone else runs into the same issue.
