### ISSUE TITLE
iOS: JsonSerializationException: Cannot deserialize readonly or fixed size dictionary: System.Collections.Generic.IReadOnlyDictionary

### ISSUE THREAD

**Issue by Zorrendor** [RageAgainstThePixel/com.openai.unity#147]
<img width="507" alt="ExceptioniOS" src="https://github.com/RageAgainstThePixel/com.openai.unity/assets/5512204/70dd9fa4-154d-40ea-bf59-43f83fba8157">

Having exception with serialization metadata on iOS, works in Unity Editor and Android.

Unity 2022.3.14f
Managed stripping level: Minimal

I believe the issue is with stripping backend which is il2cpp for iOS and Mono for Android. Somehow, on iOS doesn't support serialization of:
```csharp
        [Preserve]
        [JsonProperty("metadata")]
        public IReadOnlyDictionary<string, string> Metadata { get; }
```
        
Tried to pass null, empty Dictionary, both didn't work

**Comment by StephenHodgson** [comment]
Try adding a link.xml with the missing types

**Comment by StephenHodgson** [comment]
https://docs.unity3d.com/Manual/ManagedCodeStripping.html

**Comment by StephenHodgson** [comment]
If you can figure out which type is missing I'll add it to the package link.xml

**Comment by Zorrendor** [comment]
Thank you Stephen for fast response. Yes, I tried different types, the whole OpenAI namespace, it didn't work out. I think the issue is not with stripping but with deserialization IReadOnlyDictionary itself. It can't deserialise metadata but somehow works fine on Android. 
I will try to make a build for Android with il2cpp and check if the issue reproduces.

**Comment by StephenHodgson** [comment]
It would not reproduce because I use this in my production build that's in the app store

**Comment by StephenHodgson** [comment]
I'm unfamiliar with iOS but it definitely seems as though a type is getting stripped from the build somehow.

Let me know what you can find and I'll implement a fix if possible.

**Comment by Zorrendor** [comment]
I've just built for Android with il2cpp setting and having the same deserialization exception with IReadOnlyDictionary metadata. 
Mono works without issues.

Could you please try to build for Android or other platform with il2cpp scripting backend and to check if you can reproduce the issue?

**Comment by StephenHodgson** [comment]
Yes I built for il2cpp Android daily.

Since I don't use the assistants API in my production builds just yet I'll have to probably write up something and double check this specific thing. It could be maybe the deserialized type is incorrect.

**Comment by kripper10** [comment]
I am having the same issue when building to Quest device (Android, APK)
The weird thing is that it works fine when I run directly on PC but not on  Quest, 
I updated to 7.1.1 but still seems to be an issue.

**Comment by StephenHodgson** [comment]
What .NET compatibility are you guys targeting .net standard or .net framework?

https://stackoverflow.com/questions/31413564/how-to-deserialize-into-ireadonlydictionary-with-c

**Comment by StephenHodgson** [comment]
Also I need a full stack trace, the image screenshot doesn't really help me out too much. 

I did notice that I was missing a `[Preserve]` attribute from `MessageResponse` but from the screen shot and reports I cannot fully understand _which_ member has the deserialization issue.

**Comment by StephenHodgson** [comment]
let me know if 7.1.2 works for you or not after making sure you're using .net framework. I'll reopen if needed.

**Comment by kripper10** [comment]
Thanks for the quick response, unfortunately it's still throwing exception, I've changed to the .net framework and updated to 7.1.2 here is the trace:
Cannot deserialize readonly or fixed size dictionary:
System.Collections.Generic.IReadOnlyDictionary'2[System.String,System.STring].Path'metadate',line17, position 16

**Comment by StephenHodgson** [comment]
I need the whole stock trace

**Comment by kripper10** [comment]
StackTrace error is  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x00000] in <00000000000000000000000000000000>:0
12-16 17:13:14.762 13489 13506 I Unity   :   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues (Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <00000000000000000000000000000000>:0
12-16 17:13:14.762 13489 13506 I Unity   :   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serializa

**Comment by Zorrendor** [comment]
I managed to reproduce issue and created test class for it, on iOS JsonConvert.DeserializeObject for IReadOnlyDictionary doesn't work, probably should be replaced with Dictionary<string, string>.

Here is test class:

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Newtonsoft;
using Newtonsoft.Json;
using OpenAI;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;
using Utilities.Rest.Extensions;
using UnityEngine.Scripting;

class ReadOnlyTest
{
    [Preserve]
    [JsonConstructor]
    public ReadOnlyTest(
    [JsonProperty("metadata")] IReadOnlyDictionary<string, string> metadata)
    {
        Metadata = metadata;
    }

    [Preserve]
    [JsonProperty("metadata")]
    public IReadOnlyDictionary<string, string> Metadata { get; }
}

class DictionaryTest
{
    [Preserve]
    [JsonConstructor]
    public DictionaryTest(
    [JsonProperty("metadata")] Dictionary<string, string> metadata)
    {
        Metadata = metadata;
    }

    [Preserve]
    [JsonProperty("metadata")]
    public Dictionary<string, string> Metadata { get; }
}

public class TestSerialization : MonoBehaviour
{
    private Dictionary<string, string> bla = new Dictionary<string, string>();

    private void Awake()
    {
        bla["etst"] = "3232";
        bla["lala"] = "lolo";
    }

    public void Test1()
    {
        Debug.Log("Test1");
        var settings = new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            DefaultValueHandling = DefaultValueHandling.Ignore,
            Converters = new List<JsonConverter>
            {
                new StringEnumConverter(new SnakeCaseNamingStrategy())
            },
            ContractResolver = new EmptyToNullStringContractResolver()
        };

        

        string value = JsonConvert.SerializeObject(new ReadOnlyTest(bla), settings);
        Debug.Log("SerializeObject : " + value);
        ReadOnlyTest readOnlyTest = JsonConvert.DeserializeObject<ReadOnlyTest>(value);


        Debug.Log("DeserializeObject: ");
        foreach (var pair in readOnlyTest.Metadata)
        {
            Debug.Log(pair.Key + "  " + pair.Value);
        }
    }

    public void Test2()
    {
        Debug.Log("Test2");
        var settings = new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore,
            DefaultValueHandling = DefaultValueHandling.Ignore,
            Converters = new List<JsonConverter>
            {
                new StringEnumConverter(new SnakeCaseNamingStrategy())
            },
            ContractResolver = new EmptyToNullStringContractResolver()
        };
        string value = JsonConvert.SerializeObject(new DictionaryTest(bla), settings);
        Debug.Log("SerializeObject : " + value);

        DictionaryTest dictionaryTest = JsonConvert.DeserializeObject<DictionaryTest>(value);
        Debug.Log("DeserializeObject: ");
        foreach (var pair in dictionaryTest.Metadata)
        {
            Debug.Log(pair.Key + "  " + pair.Value);
        }
    }
}
`

With Test1 click having the same error: 
<img width="512" alt="TEST1" src="https://github.com/RageAgainstThePixel/com.openai.unity/assets/5512204/b8f54f0e-5bc9-45a7-9eb3-1aa1fee75da7">

**Comment by StephenHodgson** [comment]
Don't know if I can deal with these screenshots 😅
Any chance you can paste the actual text?

**Comment by StephenHodgson** [comment]
Can we keep the property accessor read only and have the contractor be a dictionary?

**Comment by Zorrendor** [comment]
> Don't know if I can deal with these screenshots 😅 Any chance you can paste the actual text?

Sure, the next one will be as text :D

**Comment by Zorrendor** [comment]
> Can we keep the property accessor read only and have the contractor be a dictionary?

This one works on iOS:

```
class ReadOnlyTest
{
    [Preserve]
    [JsonConstructor]
    public ReadOnlyTest(
    [JsonProperty("metadata")] Dictionary<string, string> metadata)
    {
        Metadata = metadata;
    }

    [Preserve]
    [JsonProperty("metadata")]
    public IReadOnlyDictionary<string, string> Metadata { get; }
}
```

**Comment by StephenHodgson** [comment]
> This one works on iOS:

Great I'll push out that release now.

**Comment by kripper10** [comment]
That's working now, great work. thx
