### ISSUE TITLE
Bad performance when calling the constructor AudioTranscriptionRequest(AudioClip) 

### ISSUE THREAD

**Issue by WizardHsuWeiChe** [RageAgainstThePixel/com.openai.unity#149]
I am using OpenAI 7.0.1 in Unity 2021.3.23. The running performance goes down seriously when calling the AudioTranscriptionRequest(AudioClip) constructor. The issue appeared after updating the openAI.unity from 5.0 to 7.0. After investigation, the performance issue comes from using the EncodeToOggVorbis() in the constructor. I switched back to use the EncodeToWav, and then the issue was solved.

**Comment by StephenHodgson** [comment]
If performance is critical for you, it may be better to just save it to disk and use the path as a reference in the constructor for now.

**Comment by StephenHodgson** [comment]
I wouldn't mind going back to the wav encoder, but [some people did report issues with it](#131) in the past.

**Comment by StephenHodgson** [comment]
Fixed wav package. Gonna do one more update for OGG with the breaking changes, and revert back to using wav in the next release
