### ISSUE TITLE
Error when using the library on a Meta Quest 3

### ISSUE THREAD

**Issue by GitHubUsername1** [RageAgainstThePixel/com.openai.unity#153]
# Bug Report

## Overview
When using this library to create an assistant in a Meta Quest 3 app there is an error. There is no error during compile time or when the code is ran in the Unity Editor. Here is the code that is causing the error : 

`public async Task SetupAssistant()
{
api = new OpenAIClient();

assistant = await api.AssistantsEndpoint.CreateAssistantAsync(
    new CreateAssistantRequest(
        name: "Jen",
        instructions: "You are a helpful assistant.",
        model: "gpt-4-1106-preview"));
//other code here, this code is never reached as the execution hangs on this line above`

The cmd line output when I use ADB to log the apps output is (see image): 
12-17 17:36:04.195 30399 30421 E Unity   : An error occurred in SetupAssistant: Cannot deserialize readonly or fixed size dictionary: System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.String]. Path 'metadata', line 11, position 16.

## To Reproduce
Create a Unity project, Android platform, build and run on Meta Quest 3.

## Expected behavior
The assistant to be created.

## Screenshots
![1JPG](https://github.com/RageAgainstThePixel/com.openai.unity/assets/6526207/1e14213c-9d5c-47d6-b26b-b806ea28986a)

## Additional context
This error doesn't occur when the app is played in the Unity Editor.

**Comment by StephenHodgson** [comment]
Fixed in lastest release 7.1.2
