### ISSUE TITLE
Can Chat Vision upload a local image?

### ISSUE THREAD

**Issue by GitHubUsername1** [RageAgainstThePixel/com.openai.unity#157]
# Question
Can Chat Vision upload a local image?

## Overview
The Chat Vision instructions state an url or a 2D texture can be used to upload an image, can a local image also be uploaded? When I try i get this message : 
```json
{
"error": {
    "message": "You uploaded an unsupported image. Please make sure your image is below 20 MB in size and is of one the following formats: ['png', 'jpeg', 'gif', 'webp']."
    }
}
```

## To Reproduce
```csharp
private async void ChatGPTVision(string base64_image)
{
    TextMeshPro tmpText = initializationTextMessage.GetComponent<TextMeshPro>();
    tmpText.text = "Analysing...";
    initializationTextMessage.SetActive(true);

    var apiVision = new OpenAIClient();
    var messages = new List<OpenAI.Chat.Message>
    {
        new OpenAI.Chat.Message(Role.System, "You are a helpful assistant."),
        new OpenAI.Chat.Message(Role.User, new List<OpenAI.Chat.Content>
        {
            "What's in this image?",
            new ImageUrl("data:image/jpg; base64," + base64_image, ImageDetail.Low)
        })
    };
    var chatRequest = new ChatRequest(messages, model: "gpt-4-vision-preview");
    var response = await apiVision.ChatEndpoint.GetCompletionAsync(chatRequest);
```
I've tried to go by the docs on the openai website that state for Python : 

```python
"image_url": {
            "url": f"data:image/jpeg;base64,{base64_image}"
```

## Screenshots
![Capture](https://github.com/RageAgainstThePixel/com.openai.unity/assets/6526207/3fd30cf3-6a6c-441f-8968-8f8e04d45980)

## Additional context
I'm converting the image to 64base format with 
```csharp
return Convert.ToBase64String(File.ReadAllBytes(imagePath));
```
the image is a .jpg. The size is well below 20MB, it's 1440 x 1440.

**Comment by StephenHodgson** [comment]
Yes it is supported.

Check the message. It seems something is off about your image.

**Comment by StephenHodgson** [comment]
Try passing in the image directly as texture2D

**Comment by StephenHodgson** [comment]
For context this is how this plugin has implemented it.

https://github.com/RageAgainstThePixel/com.openai.unity/blob/7c619b8f68e6cd379a54f8c9986b89fed9d69f5a/OpenAI/Packages/com.openai.unity/Runtime/Chat/Content.cs#L21

**Comment by GitHubUsername1** [comment]
Fantastic Stephen thankyou, I passed it in directly as a 2D texture, all good. Thanks for context too, next time I'll have a peek under the hood first so to speak. Thanks again.
