### ISSUE TITLE
Custom Assistant in Sample ChatBehaviour

### ISSUE THREAD

**Issue by chameleon-training** [RageAgainstThePixel/com.openai.unity#162]
I have been searching for a long time until I came across your code. I am looking for a way to use the assistant I trained with OpenAI via the API in Unity. I installed the package and got an overview with the sample. I am really impressed with your work. I have tried to extend the sample so that I can access my assistant, but unfortunately, I failed. Can you tell me what I need to adjust in the sample?

I have studied your documentation, but unfortunately, I'm struggling to get started as the topic of assistant + threads together is very complicated.

It would be a dream if you could extend the Sample ChatBehaviour so that one could enter the ID of their own assistant.

If that's too much to ask, I can absolutely understand. In that case, it would at least be helpful if you could explain the implementation startup in the documentation a bit more for dummies. ;-)

**Comment by neohun** [comment]
`
public static class OpenAIEx {

    static readonly string apiKey = "yourApiKey"; 

    /// <summary> Create an assistant thread and run for the message. </summary>
    /// <param name="message"> The input message that you want to send to assistant. </param>
    /// <param name="assistantID"> Assistant ID </param>
    /// <returns> Run response when it's complete. </returns> 
    public static async Task<RunResponse> AssistantThread(string message, string assistantID) {
        var api = new OpenAIClient(apiKey);
        var assistant = await api.AssistantsEndpoint.RetrieveAssistantAsync(assistantID);
        // create a thread as async
        var thread = await api.ThreadsEndpoint.CreateThreadAsync();
        // create the message in the thread as async. 
        _ = await thread.CreateMessageAsync(message);

        // run the thread to return a response
        var run = await thread.CreateRunAsync(assistant);
        // write the run status to console just for clarity. 
        Debug.Log($"[{run.Id}] {run.Status} | {run.CreatedAt}");

        //  wait for run to complete to return the result. 
        run = await run.WaitForRunCompleteAsync();
        // return the run response to retrieve the message. 
        return run;
    }


    static async Task<RunResponse> WaitForRunCompleteAsync(this RunResponse run) {
        // wait till run response complete
        while (!run.IsComplete()) {
            run = await run.WaitForStatusChangeAsync();
            // debug to see steps
            Debug.Log($"[{run.Id}] status: {run.Status} | {run.CreatedAt}");
        }
        // return the response. 
        return run;
    }


    /// <summary> Check whether the run response is complete. </summary> 
    static bool IsComplete(this RunResponse runResponse) {
        // return as complete if the thread is not running anymore. (not in progress, queue etc.) 
        // so even if it's failed or cancelled etc. it'll return complete,
        // this way you can continue to process the response accordingly. 
        return (runResponse.Status == RunStatus.Cancelled
                || runResponse.Status == RunStatus.Expired
                || runResponse.Status == RunStatus.Failed
                || runResponse.Status == RunStatus.Completed
                || runResponse.Status == RunStatus.RequiresAction);
    }

}

`

`
// *** Example Usage ***
async void Run() {

    string inputMessage = "your message";
    // pass your message and assistantID to get the response. 
    var result = await OpenAIEx.AssistantThread(inputMessage, "yourAssistantID");
    // list the messages from the result. 
    var messages = await result.ListMessagesAsync();
    // reverse the list because the first message is the last response. 
    var allMessages = messages.Items.Reverse().ToList();

    // write all messages for the run. 
    foreach (var message in allMessages) {
        // write the message role and content to console. 
        Debug.Log($"{message.Role}: {message.PrintContent()}");
    }
}

`

**Comment by neohun** [comment]
Also I want to point a minor issue while I'm here. It's about Items property of "ListResponse" which you use for parsing "data" of the response but I think it causes confusion because I was following some tutorials which use python API and it's called as "data" there and it was hard to find as I had to look all properties one by one. I think you can create another property as "data" and make "Items" obsolete just for the sake of clarity and parity with Python API.

**Comment by StephenHodgson** [comment]
Just some notes about example:

Probably better not to use a static class since you may need different endpoints, especially for Azure.

It's generally frowned upon to discard your tasks `_ = await Run.Task;` because you may not properly bubble up errors and handle exceptions correctly.

Instead always use try/catch, especially in unity, so that exceptions are handled properly and don't get stuck in the task queue and execute continuously.

**Comment by neohun** [comment]
> It's generally frowned upon to discard your tasks `_ = await Run.Task;` because you may not properly bubble up errors and handle exceptions correctly.

The code was just an example but you're right so I have fixed the problems you have pointed out..
But about _ discards I have tested and there was no problem by using them because when an error is thrown by an awaited function, try-catch works for the internal errors even when a discard is used. 
Discard is just for the clarity to indicate that the return value is not used to avoid confusion.

Thanks for the library by the way It has saved us from bunch of troubles (:

**Comment by neohun** [comment]
> Thank you guys, I'll try to integrate my assistant based on that. This will definitely help me...You guys are awesome!

You are welcome, good luck.

**Comment by StephenHodgson** [comment]
> But about _ discards I have tested and there was no problem when using them because when an error is thrown by an awaited function, try-catch works for the internal errors even if a discard is used.
Discard is just for the clarity to indicate that the return value is not used to avoid confusion.

I'm telling you from experience, don't use them. It's bad practice. Instead use async void for a fire and forget, and wrap it with a try /catch.

**Comment by neohun** [comment]
> I'm telling you from experience, don't use them. It's bad practice. Instead use async void for a fire and forget method, and wrap it with a try /catch.

No it is not a bad practice I have used them for a while now and never encountered an issue. Probably you have made a mistake while using it. Similar to this question so you didn't await thus you couldn't catch the error:
https://stackoverflow.com/questions/70112120/when-using-discard-to-an-async-task-the-try-catch-does-not-catch-the-inner-e

Here is the official docs which never says a bad practice or anything about the try-catch problem:
"Discards make the intent of your code clear. A discard indicates that our code never uses the variable. They enhance its readability and maintainability."
https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/functional/discards

But if you don't want to use, sure it's your design choice. Good luck.
