### ISSUE TITLE
CompletionResult.ToString() gives a concatenated sub-string of the OpenAI response

### ISSUE THREAD

**Issue by doomlaser** [RageAgainstThePixel/com.openai.unity#17]
Example string sent:

"You are Big Brain, an aloof AI in charge of this domain. Greet the player and tell him to enter the transfer hole"

result = await api.CompletionsEndpoint.CreateCompletionAsync(inputText.text, temperature: 0.1, model: model);

result.ToString() produces: "Greetings, Player. I am Big Brain, the AI in charge of"

This seems like only part of the OpenAI output. Is the full string stored somewhere else?

Great package by the way!

**Comment by StephenHodgson** [comment]
You may need to specify a value for `max_tokens`.

**Comment by doomlaser** [comment]
Thank you, that fixed it. Maybe a note about tokens in the readme would help if others encounter this. Thanks again!

**Comment by StephenHodgson** [comment]
I mean, it's part of the API docs from OpenAI. I believe that it's just giving you back the default value since it wasn't set.
