### ISSUE TITLE
CreateTranscriptionAsync in the same second

### ISSUE THREAD

**Issue by wouterswim** [RageAgainstThePixel/com.openai.unity#181]
Found an issue when creating more than one CreateTranscriptionAsync per second that it fails.
Might have something to do with filename in temp folder. When I put a delay to creating all keeps working well.
Sorry for the short msg, kids here and stuff :)

**Comment by StephenHodgson** [comment]
Thanks for reporting, I'll take a look and see what might be causing this issue.

Can you send me a code snippet for repro?

**Comment by wouterswim** [comment]
This is the error I get (it happened very occasionally until I added a delay to the generation...).
It seems to be trying to overwrite the existing file because file with same name already exists.

**ERROR**
RestException: [POST:0] file:///C:/Users/hello/AppData/Local/Temp/Pxxxxxxxe/Axxxxxr/download_cache/Nova-20240202T081616.mp3 Failed!
[Headers]
Invalid Headers: Invalid Headers
[Errors]
Invalid HTTP Method
***

Maybe adding milliseconds  could help solve this?
var clipName = $"{request.Voice}-{DateTime.UtcNow:yyyyMMddThhmmssfff}.{ext}";

Ideally the file would not be written to disk but just stored in memory until discarded?


**YOUR CODE**
public async Task<Tuple<string, AudioClip>> CreateSpeechAsync(SpeechRequest request, CancellationToken cancellationToken = default)
        {
            var audioFormat = request.ResponseFormat switch
            {
                SpeechResponseFormat.MP3 => AudioType.MPEG,
                _ => throw new NotSupportedException(request.ResponseFormat.ToString())
            };
            var ext = request.ResponseFormat switch
            {
                SpeechResponseFormat.MP3 => "mp3",
                _ => throw new NotSupportedException(request.ResponseFormat.ToString())
            };
            var payload = JsonConvert.SerializeObject(request, OpenAIClient.JsonSerializationOptions);
            var clipName = $"{request.Voice}-{DateTime.UtcNow:yyyyMMddThhmmss}.{ext}";
            var clip = await Rest.DownloadAudioClipAsync(
                GetUrl("/speech"),
                audioFormat,
                UnityWebRequest.kHttpVerbPOST,
                clipName,
                payload,
                parameters: new RestParameters(client.DefaultRequestHeaders),
                debug: EnableDebug,
                cancellationToken: cancellationToken);
            Rest.TryGetDownloadCacheItem(clipName, out var cachedPath);
            return new Tuple<string, AudioClip>(cachedPath, clip);
        }
