### ISSUE TITLE
Add Fine-Tuning endpoints

### ISSUE THREAD

**Issue by natemakesgames** [RageAgainstThePixel/com.openai.unity#20]
Hello, is there a way to "fine-tune" or "train" any of the models that I can use with this plugin, using new data?

I found the official Open-AI fine-tuning tutorial, should I just follow that? Would there be any extra steps? Thank you.

**Comment by StephenHodgson** [comment]
I have not added [fine tuning endpoints](https://beta.openai.com/docs/api-reference/fine-tunes), as I didn't think they were really relevant to Unity specifically since it's for training models.

Pull requests are welcome.

**Comment by natemakesgames** [comment]
Thank you for your quick response. I apologize because I am a complete beginner with this API and plugin. Even though you have not added "fine tuning endpoints" yet, would it still be possible to train a model with fine tuning externally, and then use that fine-tuned model in Unity? And if so, what would the steps be for that? Or is that not possible yet without major changes to this plugin?

**Comment by StephenHodgson** [comment]
> would it still be possible to train a model with fine tuning externally, and then use that fine-tuned model in Unity?

Yes that is correct
