### ISSUE TITLE
Minimum compatible Unity version?

### ISSUE THREAD

**Issue by doomlaser** [RageAgainstThePixel/com.openai.unity#22]
Do you know what the minimum required version of Unity is for this package to work? It appears not to work in 2019.4.16f1 at least

**Comment by StephenHodgson** [comment]
https://openupm.com/packages/com.openai.unity/

![image](https://user-images.githubusercontent.com/13334553/214924352-0f6c607d-9e45-4033-adef-27c090591406.png)

https://github.com/RageAgainstThePixel/com.openai.unity/blob/ea42d3248e136564fa3007293cadf10112a25152/OpenAI/Packages/com.openai.unity/package.json#L7
