### ISSUE TITLE
no support for new model, "gpt-3.5-turbo"

### ISSUE THREAD

**Issue by doomlaser** [RageAgainstThePixel/com.openai.unity#35]
# Bug Report
When I try to suggest OpenAI's latest model, ""gpt-3.5-turbo", I get an error that the model is not found. Since I am sending a string request to openai, shouldn't support for that not have to be hardcoded? In any case, I can't use the latest model with this package.

## To Reproduce
model = await api.ModelsEndpoint.GetModelDetailsAsync("gpt-3.5-turbo");

Result: HttpRequestException: CreateCompletionAsync Failed! HTTP status code: NotFound.

**Comment by StephenHodgson** [comment]
I' already been working on it all day
