### ISSUE TITLE
MaxTokens parameter is not set in constructor class

### ISSUE THREAD

**Issue by mati-eperez** [RageAgainstThePixel/com.openai.unity#38]
The MaxTokens var is not set in the constructor from the class ChatRequest. This may cause money issues.

**Comment by StephenHodgson** [comment]
https://github.com/RageAgainstThePixel/com.openai.unity/blob/a6ac5e70ee9ec3ca20f49bd60e9560682066215f/OpenAI/Packages/com.openai.unity/Runtime/Chat/ChatRequest.cs#L39
