### ISSUE TITLE
System.ArgumentException: gpt-3.5-turbo is not supported

### ISSUE THREAD

**Issue by Gustorvo** [RageAgainstThePixel/com.openai.unity#44]
`System.ArgumentException: gpt-3.5-turbo is not supported` when trying to make a completion request 
Plz add gpt-3.5-turbo to the list of supported models. According to documentation, it should be supported.

**Comment by StephenHodgson** [comment]
Sounds like you're using the wrong endpoint.

Only `ChatEndpoint` supports turbo.

**Comment by StephenHodgson** [comment]
https://platform.openai.com/docs/models/model-endpoint-compatability

**Comment by Gustorvo** [comment]
you're right...thank you for pointing out!
