### ISSUE TITLE
The latest version OpenAI 3.1.1 can not be downloaded

### ISSUE THREAD

**Issue by scv9487** [RageAgainstThePixel/com.openai.unity#45]
# Bug Report

## Overview
The latest version OpenAI 3.1.1 can not be downloaded 

## To Reproduce
1. Window -> Package Manager
2. click 'Add Package from git url'
3. Put git url 'https://github.com/RageAgainstThePixel/com.openai.unity.git#upm'
4. It tries to install but fails (nothing happens)

## Expected behavior
latest versions can be downloaded by Unity Package Manager

## Screenshots
![image](https://user-images.githubusercontent.com/57919809/224223274-1290554e-7e21-49c4-a6aa-3696ac3eb713.png)
(When using git to download)

![image](https://user-images.githubusercontent.com/57919809/224222685-27718c73-b100-4629-8299-d6f8322577b4.png)
(Happens same when using OpenUPM to download)

## Additional context
I was able to install OpenAI 3.03 instead of OpenAI 3.1.1
But, it failed when using 'completions' api when the model was GPT3_5_Turbo (instead, Davinci model worked well as explained in the description)

**Comment by StephenHodgson** [comment]
That is because you're using Git download instead of OpenUPM Package registry. 

You are required to add all the other git dependencies on your own.

**Comment by StephenHodgson** [comment]
Use this method instead: 
https://github.com/RageAgainstThePixel/com.openai.unity#via-unity-package-manager-and-openupm

**Comment by scv9487** [comment]
I first tried to install by OpenUPM (as your link above), so I tried the git download as an alternative.
After seeing your comment I found out that I didn't have **'com.utilities.encoder.wav'** which is a dependency (but not explained in description)
So I tried adding 'https://github.com/RageAgainstThePixel/com.utilities.encoder.wav' by OpenUPM but it didn't show up in the Package manager as screenshot below (tired to download by git, but it didn't work either)
![image](https://user-images.githubusercontent.com/57919809/224226592-85daa149-ee32-4315-b810-6c0fa63736ef.png)

Please answer to one more simple question,
About GPT3_5_Turbo not working for completions, I show your comment on other ticket that 'Only ChatEndpoint supports turbo.'
Since I want to use the completions, I would like to try using Davinci. But I'm confused that if I set 'Davinci' as model, **does it mean the 'text-davinci-003'(GPT3.5) or davinci(GPT3.0)?**

Thanks a lot in advance.

**Comment by StephenHodgson** [comment]
Go back and follow the steps to add the scoped registry in your project's settings.

**Comment by StephenHodgson** [comment]
The dependencies are automatically resolved when using OpenUPM scoped registry
