### ISSUE TITLE
ChatEndpoint.StreamCompletionAsync ends up with Choices[0].Message as Null

### ISSUE THREAD

**Issue by LanceCAbson** [RageAgainstThePixel/com.openai.unity#58]
# Bug Report

## Overview
When using ChatEndpoint.StreamCompletionAsync the streaming works fine, but when the streaming is finished the ChatResponse contains some nulls.

## To Reproduce
1. Call ChatEndpoint.StreamCompletionAsync
2. When result is finished
3. Look at the ChatResponse
4. See the null

## Expected behavior
After the ChatEndpoint.StreamCompletionAsync is finished I would expect the ChatResponse to not contain any null values.

## Additional context
Are you going to add Error handling please?

**Comment by StephenHodgson** [comment]
Please provide an example and repro steps

**Comment by StephenHodgson** [comment]
Please provide more info on repro for future assistance
