### ISSUE TITLE
Consider using UniTask?

### ISSUE THREAD

**Issue by tomkail** [RageAgainstThePixel/com.openai.unity#64]
Hello! First, thanks for keeping this updated so fast! Easily my fav GPT wrapper for Unity.

Wanted to suggest moving to UniTask (https://github.com/Cysharp/UniTask) to handle async/await code. UniTask is by far the most popular solution out there, and I imagine will be familiar/already included by many devs. They're also in active discussion with Unity, so I wouldn't be surprised to hear that they adopt it (or at least something very similar) for future versions of the engine.

**Comment by StephenHodgson** [comment]
I'm actually not a fan of uni task

**Comment by StephenHodgson** [comment]
Thanks for the recommendation but I may not be making this change myself.

**Comment by StephenHodgson** [comment]
I've also tried to make sure that this repo almost directly aligns/is mirrored by https://github.com/RageAgainstThePixel/OpenAI-DotNet
