### ISSUE TITLE
Dall-E 2 Azure not support

### ISSUE THREAD

**Issue by duyquang957** [RageAgainstThePixel/com.openai.unity#77]
# Feature Request

OpenAIAuthentication.LoadFromDirectory not support for Azure OpenAI. I tried and get 400 bad request. can use via script.
I use Azure OpenAI api to generate image, edit image and get bad request 404 because different format.
`https://resourceName.openai.azure.com/dalle/text-to-image?api-version=2022-08-03-preview
{
    "caption": "USER_PROMPT_GOES_HERE",
    "resolution": "1024x1024"
}`
I use Azure OpenAI because in my country OpenAI is not available.

**Comment by StephenHodgson** [comment]
The Doll-E endpoints are not available on azure.

I believe it only supports embeddings, completions, and chat.

**Comment by StephenHodgson** [comment]
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/overview#features-overview

**Comment by duyquang957** [comment]
It available here for East US: https://oai.azure.com/portal/dalle-playground?azureopenai_dalle_preview=true

**Comment by StephenHodgson** [comment]
This link did not work for me

**Comment by StephenHodgson** [comment]
I'll reopen this for now to take a look at it and see if the semantic kernel takes advantage of this. If it does I'll port over any fixes.

**Comment by StephenHodgson** [comment]
If you have any documentation links it would be very helpful
