### ISSUE TITLE
when i use text completion is no error, but if i want to use chat error like this. Please helpme

### ISSUE THREAD

**Issue by satriagilang80** [RageAgainstThePixel/com.openai.unity#87]
HttpRequestException: GetCompletionAsync Failed! HTTP status code: NotFound | Response body: {"error":{"code":"404","message": "Resource not found"}}
OpenAI.Extensions.ResponseExtensions.ReadAsStringAsync (System.Net.Http.HttpResponseMessage response, System.Boolean debug, System.String methodName)

**Comment by StephenHodgson** [comment]
Which model are you using?

**Comment by StephenHodgson** [comment]
If you're trying to use chat GPT you need to use the chat endpoint.

**Comment by StephenHodgson** [comment]
https://platform.openai.com/docs/models/model-endpoint-compatibility
