### ISSUE TITLE
error CS0006: Metadata file 'Library/PackageCache/com.unity.ext.nunit@2.0.3/net35/unity-custom/nunit.framework.dll' could not be found

### ISSUE THREAD

**Issue by imineti** [RageAgainstThePixel/com.openai.unity#93]
Error instantly after installing

Installed in the recommended way using the package manager in the project settings using OpenUPM name URL and scopes and then installed using the package manager window, instantly I have two errors saying the same thing.

'error CS0006: Metadata file 'Library/PackageCache/com.unity.ext.nunit@2.0.3/net35/unity-custom/nunit.framework.dll' could not be found'
'error CS0006: Metadata file 'Library/PackageCache/com.unity.ext.nunit@2.0.3/net35/unity-custom/nunit.framework.dll' could not be found'

Double-clicking on them does nothing.

I'm using Unity 2022.3.2f1 <DX11> on Windows 11.

![OpenAI Error](https://github.com/RageAgainstThePixel/com.openai.unity/assets/79813551/205c8779-9617-41b3-bef1-0a0537366a0a)

**Comment by StephenHodgson** [comment]
What happens when you restart the editor?
Does the error go away?

I've seen this pop up intermittently but it's always been after I've already installed burst compiler, or universal pipeline

**Comment by imineti** [comment]
I restarted Unity and the errors disappeared. I already had both burst compiler and universal pipeline installed before I installed your OpenAI package so that does seem to be why, for whatever reason a restart seems to fix it. Thank you.

**Comment by StephenHodgson** [comment]
Yeah I've had the same issue too, but it doesn't seem to be a long-lasting error.

**Comment by udulabenaragama** [comment]
same happened to me too after updating the collections package
and restarting seems to have fixed it

**Comment by StephenHodgson** [comment]
Yup it's a unity bug
