### ISSUE TITLE
Can't import using OpenAI.Chat; or using OpenAI.Models;

### ISSUE THREAD

**Issue by geangs** [RageAgainstThePixel/com.openai.unity#99]
I've installed this package as described using UPM and unity package manager but I can't use any of the code. What am I missing? Thank you

**Comment by StephenHodgson** [comment]
What exactly is happening?

**Comment by geangs** [comment]
I get "Cannot resolve symbol 'OpenAI'" when using OpenAI.Chat; I installed the package as described in the documentation and I'm not sure what I'm doing wrong. The unity package manger screen shows all packages as installed.

**Comment by StephenHodgson** [comment]
Are you using any assembly definitions?

**Comment by geangs** [comment]
I am using a new project without any assembly definitions

**Comment by StephenHodgson** [comment]
What version of unity are you using?

**Comment by StephenHodgson** [comment]
Can you also please send me a screenshot of your packages installed in the project, and your package manager settings

**Comment by geangs** [comment]
I'm using unity 2022.3.4f1

![strats on table](https://github.com/RageAgainstThePixel/com.openai.unity/assets/46005593/cb643517-612c-4ed6-b1aa-f60988375a86)
![Screenshot_71](https://github.com/RageAgainstThePixel/com.openai.unity/assets/46005593/a038b5c0-5a57-4884-9d69-1184375a968a)

**Comment by StephenHodgson** [comment]
Well that looks good to me.

Can you share the class that you've written?

**Comment by StephenHodgson** [comment]
Have you tried importing the sample scene?
